# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
            ROLE_ADMIN:       ROLE_ADMIN
            ROLE_SUPER_ADMIN: ROLE_ADMIN
            ROLE_USER:        ROLE_USER

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
                    id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: fos_user_security_check
                login_path: fos_user_security_login

            logout:
                path: fos_user_security_logout
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/admin, role: ROLE_ADMIN }
        - { path: ^/en/admin, role: ROLE_ADMIN }
        - { path: ^/fr/preresa, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/preresarapide, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/payment, role: IS_AUTHENTICATED_FULLY }
